name: cheesegang
description: "cheese gang"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.3.2

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.2
  gap: ^3.0.1
  glassmorphism: ^3.0.0
  video_player: ^2.10.1
  model_viewer_plus: ^1.9.3
  dio: ^5.9.0
  shared_preferences: ^2.5.3
  skeletonizer: ^2.1.0+1
  image_picker: ^1.2.1
  shimmer: ^3.0.0
  flutter_bloc: ^9.1.1
  hive_flutter: ^1.1.0
  equatable: ^2.0.7
  hive_ce: ^2.18.0
  hive_ce_flutter:  ^2.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  mockito: ^5.6.1
  build_runner: ^2.10.4
  hive_ce_generator: ^1.11.1

flutter:


  uses-material-design: true

  assets:
    - assets/logo/
    - assets/splash/
    - assets/test/
    - assets/detail/
    - assets/icon/
    - assets/video/
    - assets/3d/



  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
